version: "3.9"
services:
  rails_app_1: &app1
    image: rails_app_1
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mysql
      #- elasticsearch
      #- couchdb
    volumes:
      - ".:/app"
  rails_app_1_debug:
    <<: *app1
    ports:
      - "3000:3000"
      - "1234:1234"
    command:
      - bundle
      - exec
      - rdebug-ide
      - --host
      - 0.0.0.0
      - --port
      - "1234"
      - --dispatcher-port
      - "26162"
      - --
      - bin/rails
      - s
      - -b
      - 0.0.0.0
#  rails_app_2:
#    image: rails_app_2
#    build:
#      dockerfile: Dockerfile
#    ports:
#      - "3001:3000"
  redis:
    image: "redis:alpine"
  mysql:
    image: mysql
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example

  #elasticsearch:
  #  image: elasticsearch
  #couchdb:
  #  image: couchdb